[tox:tox]
minversion = 4.31.0
isolated_build = true
skip_missing_interpreters = true
env_list =
  py313,
  py314,

[testenv]
groups =
  dev
allowlist_externals =
  pdm
  bandit
  flake8
  pytest
  radon
  vulture
commands =
  pytest --cov

[testenv:py313]
basepython = python3.13

[testenv:py314]
basepython = python3.14

[testenv:lint]
commands = flake8 src tests

[testenv:security]
commands = bandit -r src

[testenv:complexity]
commands =
  radon cc --total-average --no-assert src tests
  radon mi --show src tests
  radon hal src tests

[testenv:deadcode]
commands = vulture --min-confidence src


[pytest]
addopts = -rA
testpaths =
  tests
python_files =
  tests-*.py


[coverage:run]
branch = true
source =
  gitcontext


[coverage:report]
show_missing = true
skip_covered = false
precision = 0
fail_under = 100


[coverage:xml]
output = coverage.xml


[coverage:html]
directory = htmlcov


[flake8]
statistics      = true
tee             = true
max-complexity  = 8
max-line-length = 99
exclude =
    .git,
    __pycache__,
    setup.cfg,
    .pytest_cache,
    .history,
    .venv,
    .pytest_cache,
    .tox,
    dist,
    build,
